sudo: required
dist: trusty
language: cpp
cache: ccache
matrix:
  include:
  - os: linux
    compiler: gcc-6
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-6
        - g++-6
        - libpython3-dev
        - python3
    env:
    - MATRIX_EVAL="export CC=gcc-6 && CXX=g++-6 && CONFIG=Debug"

  - os: linux
    compiler: gcc-6
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-6
        - g++-6
        - libpython3-dev
        - python3
    env:
    - MATRIX_EVAL="export CC=gcc-6 && CXX=g++-6 && CONFIG=Release"

  - os: linux
    compiler: gcc-7
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-7
        - g++-7
        - libpython3-dev
        - python3
    env:
    - MATRIX_EVAL="export CC=gcc-7 && CXX=g++-7 && CONFIG=Debug"

  - os: linux
    compiler: gcc-7
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-7
        - g++-7
        - libpython3-dev
        - python3
    env:
    - MATRIX_EVAL="export CC=gcc-7 && CXX=g++-7 && CONFIG=Release"

  - os: linux
    compiler: gcc-8
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-8
        - g++-8
        - libpython3-dev
        - python3
    env:
    - MATRIX_EVAL="export CC=gcc-8 && CXX=g++-8 && CONFIG=Debug"

  - os: linux
    compiler: gcc-8
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-8
        - g++-8
        - libpython3-dev
        - python3
    env:
    - MATRIX_EVAL="export CC=gcc-8 && CXX=g++-8 && CONFIG=Release"

  - os: osx
    osx_image: xcode10.1
    compiler: clang
    env:
    - MATRIX_EVAL="export CONFIG=Debug"

  - os: osx
    osx_image: xcode10.1
    compiler: clang
    env:
    - MATRIX_EVAL="export CONFIG=Release"

install:
- eval "${MATRIX_EVAL}"

script:
- mkdir build
- pushd build
- cmake -DCMAKE_BUILD_TYPE=$CONFIG ..
- make -j2
- popd
- python3 test.py
